### ISSUE TITLE
Issues from cosmosdb service team

### ISSUE THREAD

**Issue by Incarnation-p-lee** [microsoft/spring-data-cosmosdb#293]
* [x] Id alone does "not" uniquely identify the entity. It is the composition of partition key and id which can be used for uniquely identifying the entity.
@Incarnation-p-lee : The spring-data-commons provide the CRUD interface CrudRepository which defines the API in above. It is spring-data spec which out of our control.
@sophiaso : If PartitionKey is used in domain, user can define interface as findByIdAndCity(String id, String city) to achieve uniquely searching one entity.

* [x] you should not do query against collection per document save. That's very expensive. Maybe you can cache collection?
@Incarnation-p-lee : we have refined this and only createCollectionIfNoExist when Repository Bean construction

* [x] DocumentDBTEmplate.find(Query, ...):
the purpose is to execute the given query to find documents. However it first it queries against collections (master resource query) which consumes the limited master resource budget. Also it doesn't set any cross partition degree of parallelism.
@Incarnation-p-lee : we rewrote these chunk of code.

* [x] The library relies on Google Gson for json serialization. Our SDK uses org.json and jackson, ideal would be to not add a new dependency for serialization. Can you use jackson?
@Incarnation-p-lee : We have issue #267 for this, will make it more elegant when migrating to Async work done.

* [ ] __Feature__ Request/feed option setting is not configurable, #294 .
@Incarnation-p-lee : from the convention and spec of spring-data, export these kind of azure specific details to user is not a good idea. We may enhance this part if customer requires this.

* [ ] __Feature__ Only string is supported as partition key, #295.
* [x] __Feature__ I don't see any hook for throttling retry policy config, #296.
